// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baleomtsxnecrmthddcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhbGVvbXRzeG5lY3JtdGhkZGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTkxMzEsImV4cCI6MjA2NDQzNTEzMX0.cgofqIDJyhTRF06A90H5jaeoBmOjJTIkH1pvGbKFiZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);